### ISSUE TITLE
Sampling Method from Paper

### ISSUE THREAD

**Issue by KevinG1002** [xiangsheng1325/fastgae_pytorch#1]
Hi, thanks for doing this work. Very useful stuff. 

I had a question regarding your work which you should feel free to ignore if my observations are wrong. 

1) In your main training loop it seems that the sampling techniques presented in the FastGAE paper are not used and instead you opted to randomly sample nodes from the nodes list of the graph. Do you have any ideas on how you would sample subgraphs as they did in the paper using Pytorch? 

Thanks! 

PS: Are you planning on implementing the Fast G-VAE model they propose in the paper too?

**Comment by xiangsheng1325** [comment]
Hey, KevinG1002.

I want to introduce the sampling strategy I have used. The strategy contains two step: 1. sampling nodes, 2. obtaining subgraph from sampled nodes.
Therefore, my sampling operation is actually conducted on nodes instead of subgraphs.


About the node sampling method, my experimental results determined the used sampling method.
If you look at the FastGAE paper, they have analyzed the effectiveness of all sampling methods, including **degree**, **uniform** and **core**. Their findings are consistent to mine.

About the subgraph sampling algorithm, I think you can try to implement a DeepWalk algorithm to achieve walk sampling. And you can also traverse a part of the graph to obtain an induced subgraph.

PS: the subgraph sampling operations are mainly heterogeneous, which is time-consuming and hard to implement with GPU-based engine, such as PyTorch. 

If you are interested in subgraph sampling, you can look at the paper written by the **dgl** team or **UNSW database** team to see how to sample the subgraph efficiently.
